### ISSUE TITLE
Sotring the WML model fails 

### ISSUE THREAD

**Issue by tjirku** [IBM-Bluemix-Docs/ai-openscale#94]
Running the notebook from this git repo - until when the section "save and deploy the model" is called in the 3rd cell of this section it fails - giving me an error.
the cell that is bein called is
`wml_models = wml_client.repository.get_details()
model_uid = None
for model_in in wml_models['models']['resources']:
    if MODEL_NAME == model_in['entity']['name']:
        model_uid = model_in['metadata']['guid']
        break

if model_uid is None:
    print("Storing model ...")

    published_model_details = wml_client.repository.store_model(model=model, meta_props=model_props, training_data=train_data, pipeline=pipeline)
    model_uid = wml_client.repository.get_model_uid(published_model_details)
    print("Done")`

The error that i am getting says:

> wml_models = wml_client.repository.get_details()

model_uid = None

for model_in in wml_models['models']['resources']:

    if MODEL_NAME == model_in['entity']['name']:

        model_uid = model_in['metadata']['guid']

        break

​

if model_uid is None:

    print("Storing model ...")

​

    published_model_details = wml_client.repository.store_model(model=model, meta_props=model_props, training_data=train_data, pipeline=pipeline)

    model_uid = wml_client.repository.get_model_uid(published_model_details)

    print("Done")

Storing model ...
Traceback (most recent call last):
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/experiment_collection.py", line 229, in save
    r = self.repository_api.ml_assets_experiment_creation_with_http_info(experiment_input)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/apis/repository_api.py", line 154, in ml_assets_experiment_creation_with_http_info
    _return_http_data_only=params.get('_return_http_data_only'))
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py", line 377, in call_api
    response_type, auth_settings, callback, _return_http_data_only)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py", line 197, in __call_api
    post_params=post_params, body=body)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py", line 413, in request
    body=body)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/rest.py", line 222, in POST
    body=body)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/rest.py", line 190, in request
    raise ApiException(http_resp=r)
watson_machine_learning_client.libs.repo.swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Server': 'nginx', 'X-XSS-Protection': '1', 'Pragma': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Content-Type': 'application/json', 'x-global-transaction-id': 'm35rf9gpb8l3c4f0fd24259382b6mh87dfc9', 'Content-Length': '166', 'Date': 'Wed, 20 Mar 2019 07:39:01 GMT', 'Connection': 'keep-alive', 'X-WML-User-Client': 'PythonClient'})
HTTP response body: {"trace":"m35rf9gpb8l3c4f0fd24259382b6mh87dfc9","errors":[{"code":"invalid_framework_input","message":"The framework value specified: mllib, 2.4 is not supported."}]}

Traceback (most recent call last):
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/model_collection.py", line 461, in _save_spark_pipeline_model
    new_pipeline_artifact = self._create_pipeline(pipeline_artifact)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/model_collection.py", line 509, in _create_pipeline
    return self.client.pipelines.save(pipeline_artifact)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/experiment_collection.py", line 265, in save
    raise e
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/experiment_collection.py", line 229, in save
    r = self.repository_api.ml_assets_experiment_creation_with_http_info(experiment_input)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/apis/repository_api.py", line 154, in ml_assets_experiment_creation_with_http_info
    _return_http_data_only=params.get('_return_http_data_only'))
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py", line 377, in call_api
    response_type, auth_settings, callback, _return_http_data_only)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py", line 197, in __call_api
    post_params=post_params, body=body)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py", line 413, in request
    body=body)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/rest.py", line 222, in POST
    body=body)
  File "/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/rest.py", line 190, in request
    raise ApiException(http_resp=r)
watson_machine_learning_client.libs.repo.swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Server': 'nginx', 'X-XSS-Protection': '1', 'Pragma': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Content-Type': 'application/json', 'x-global-transaction-id': 'm35rf9gpb8l3c4f0fd24259382b6mh87dfc9', 'Content-Length': '166', 'Date': 'Wed, 20 Mar 2019 07:39:01 GMT', 'Connection': 'keep-alive', 'X-WML-User-Client': 'PythonClient'})
HTTP response body: {"trace":"m35rf9gpb8l3c4f0fd24259382b6mh87dfc9","errors":[{"code":"invalid_framework_input","message":"The framework value specified: mllib, 2.4 is not supported."}]}

---------------------------------------------------------------------------
ApiException                              Traceback (most recent call last)
/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/models.py in _publish_from_object(self, model, meta_props, training_data, training_target, pipeline, feature_names, label_column_names)
     56                 model_artifact = MLRepositoryArtifact(model, name=str(meta_props[self.ConfigurationMetaNames.NAME]), meta_props=meta_data, training_data=training_data, training_target=training_target,feature_names=feature_names,label_column_names=label_column_names)
---> 57             saved_model = self._client.repository._ml_repository_client.models.save(model_artifact)
     58         except Exception as e:

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/model_collection.py in save(self, artifact, query_param)
    217         else:
--> 218             return self._save_spark_pipeline_model(artifact, query_param)
    219 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/model_collection.py in _save_spark_pipeline_model(self, artifact, query_param)
    477             print(traceback.format_exc())
--> 478             raise e
    479 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/model_collection.py in _save_spark_pipeline_model(self, artifact, query_param)
    460                         else:
--> 461                             new_pipeline_artifact = self._create_pipeline(pipeline_artifact)
    462 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/model_collection.py in _create_pipeline(self, pipeline_artifact)
    508     def _create_pipeline(self, pipeline_artifact):
--> 509         return self.client.pipelines.save(pipeline_artifact)
    510 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/experiment_collection.py in save(self, artifact)
    264             print(traceback.format_exc())
--> 265             raise e
    266 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/mlrepositoryclient/experiment_collection.py in save(self, artifact)
    228                 experiment_input = self._prepare_experiment_input(artifact)
--> 229                 r = self.repository_api.ml_assets_experiment_creation_with_http_info(experiment_input)
    230                 statuscode = r[1]

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/apis/repository_api.py in ml_assets_experiment_creation_with_http_info(self, models_input, **kwargs)
    153                                             callback=params.get('callback'),
--> 154                                             _return_http_data_only=params.get('_return_http_data_only'))
    155 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only)
    376                                    body, post_params, files,
--> 377                                    response_type, auth_settings, callback, _return_http_data_only)
    378         else:

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only)
    196                                      headers=header_params,
--> 197                                      post_params=post_params, body=body)
    198 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/api_client.py in request(self, method, url, query_params, headers, post_params, body)
    412                                          post_params=post_params,
--> 413                                          body=body)
    414         elif method == "PUT":

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/rest.py in POST(self, url, headers, query_params, post_params, body)
    221                             post_params=post_params,
--> 222                             body=body)
    223 

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/libs/repo/swagger_client/rest.py in request(self, method, url, query_params, headers, body, post_params)
    189         if r.status not in range(200, 206):
--> 190             raise ApiException(http_resp=r)
    191 

ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Server': 'nginx', 'X-XSS-Protection': '1', 'Pragma': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Content-Type': 'application/json', 'x-global-transaction-id': 'm35rf9gpb8l3c4f0fd24259382b6mh87dfc9', 'Content-Length': '166', 'Date': 'Wed, 20 Mar 2019 07:39:01 GMT', 'Connection': 'keep-alive', 'X-WML-User-Client': 'PythonClient'})
HTTP response body: {"trace":"m35rf9gpb8l3c4f0fd24259382b6mh87dfc9","errors":[{"code":"invalid_framework_input","message":"The framework value specified: mllib, 2.4 is not supported."}]}

During handling of the above exception, another exception occurred:

WMLClientError                            Traceback (most recent call last)
<ipython-input-84-c116de4ecf13> in <module>()
      9     print("Storing model ...")
     10 
---> 11     published_model_details = wml_client.repository.store_model(model=model, meta_props=model_props, training_data=train_data, pipeline=pipeline)
     12     model_uid = wml_client.repository.get_model_uid(published_model_details)
     13     print("Done")

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/repository.py in store_model(self, model, meta_props, training_data, training_target, pipeline, feature_names, label_column_names)
    239         >>> stored_model_details = client.repository.store_model(trained_model_guid, meta_props=metadata, training_data=None)
    240         """
--> 241         return self._client._models.store(model, meta_props=meta_props, training_data=training_data, training_target=training_target, pipeline=pipeline, feature_names=feature_names,label_column_names=label_column_names)
    242 
    243     @docstring_parameter({'str_type': STR_TYPE_NAME})

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/models.py in store(self, model, meta_props, training_data, training_target, pipeline, version, artifactid, feature_names, label_column_names)
    510                 raise WMLClientError(u'Unsupported type: object for param model. Supported types: path to saved model, training ID')
    511             else:
--> 512                 saved_model = self._publish_from_object(model=model, meta_props=meta_props, training_data=training_data, training_target=training_target, pipeline=pipeline, feature_names=feature_names, label_column_names=label_column_names)
    513         else:
    514             if (os.path.sep in model) or os.path.isfile(model) or os.path.isdir(model):

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/watson_machine_learning_client/models.py in _publish_from_object(self, model, meta_props, training_data, training_target, pipeline, feature_names, label_column_names)
     57             saved_model = self._client.repository._ml_repository_client.models.save(model_artifact)
     58         except Exception as e:
---> 59             raise WMLClientError(u'Publishing model failed.', e)
     60         else:
     61             return self.get_details(u'{}'.format(saved_model.uid))

WMLClientError: Publishing model failed.
Reason: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Server': 'nginx', 'X-XSS-Protection': '1', 'Pragma': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Content-Type': 'application/json', 'x-global-transaction-id': 'm35rf9gpb8l3c4f0fd24259382b6mh87dfc9', 'Content-Length': '166', 'Date': 'Wed, 20 Mar 2019 07:39:01 GMT', 'Connection': 'keep-alive', 'X-WML-User-Client': 'PythonClient'})
HTTP response body: {"trace":"m35rf9gpb8l3c4f0fd24259382b6mh87dfc9","errors":[{"code":"invalid_framework_input","message":"The framework value specified: mllib, 2.4 is not supported."}]}

Any help widely appreciated !

**Comment by msochka** [comment]
@tjirku 

This is a repository for OpenScale documentation. I tagged you in two channels on Slack where you might find help for your question. I hope that is useful. I'm not able to figure your specific problem out.
