### ISSUE TITLE
Advance Python Example is missing a step

### ISSUE THREAD

**Issue by jgnoonan** [IBM-Bluemix-Docs/ai-openscale#96]
In the Provision IBM Cloud Services section, the user needs to provision a service instance of Watson OpenScale otherwise variable AIOS_GUID won't get populated and will fail.  Need to add the instructions to create a Watson OpenScale service instance.

**Comment by msochka** [comment]
It is clearly listed in the pre-requisites that the user ALREADY HAS Watson OpenScale:

https://test.cloud.ibm.com/docs/services/ai-openscale?topic=ai-openscale-crt-ov#crt-prereqs

However, we don't assume that the user has the other required IBM Cloud instances.

**Comment by msochka** [comment]
I have added the following section:

https://test.cloud.ibm.com/docs/services/ai-openscale?topic=ai-openscale-crt-ov#crt-wos-adv

**Comment by jgnoonan** [comment]
Looks perfect!!  Thanks @msochka !
